version: '3.4'
services:
# Initial setup. Run the following command first and enter a valie fitbit refresh token
# make sure the mapped logs and tokens folders exists and owned by 1000 uid, otherwise you may get permission denied error. 
# docker compose run --rm fitbit-fetch-data
# Then exit out with ctrl + c
# Then run docker compose up -d to launch the full stack
  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    restart: unless-stopped
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_BUCKET}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_TOKEN}
    volumes:
      - influxdb-data:/var/lib/influxdb2
      - influxdb-config:/etc/influxdb2
    networks:
      - fitbit-network
  
  fitbit-fetch:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fitbit-fetch
    restart: unless-stopped
    environment:
      - FITBIT_LOG_FILE_PATH=/app/logs/fitbit.log
      - TOKEN_FILE_PATH=/app/tokens/tokens.json
      - FITBIT_LANGUAGE=en_US
      - INFLUXDB_VERSION=2
      - INFLUXDB_HOST=influxdb
      - INFLUXDB_PORT=8086
      - INFLUXDB_USERNAME=${INFLUXDB_USERNAME}
      - INFLUXDB_PASSWORD=${INFLUXDB_PASSWORD}
      - INFLUXDB_DATABASE=fitbit
      - INFLUXDB_BUCKET=${INFLUXDB_BUCKET}
      - INFLUXDB_ORG=${INFLUXDB_ORG}
      - INFLUXDB_TOKEN=${INFLUXDB_TOKEN}
      - INFLUXDB_URL=http://influxdb:8086
      - FITBIT_CLIENT_ID=${FITBIT_CLIENT_ID}
      - FITBIT_CLIENT_SECRET=${FITBIT_CLIENT_SECRET}
      - FITBIT_DEVICE_NAME=${FITBIT_DEVICE_NAME}
      - AUTO_DATE_RANGE=true
      - AUTO_UPDATE_DATE_RANGE=1
      - LOCAL_TIMEZONE=${LOCAL_TIMEZONE:-America/New_York}
    volumes:
      - ./logs:/app/logs
      - ./tokens:/app/tokens
    depends_on:
      - influxdb
    networks:
      - fitbit-network
volumes:
  influxdb-data:
  influxdb-config:
  chronograf-data:

networks:
  fitbit-network:
    driver: bridge
